/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pegasus.petsoft.client;

import com.pegasus.petsoft.dal.PetsDAO;
import com.pegasus.petsoft.model.Pets;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Formatter;
import java.util.GregorianCalendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFormattedTextField;
import javax.swing.JFormattedTextField.AbstractFormatter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author marina.silva
 */
public class JFrameAddPet extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAddPet
     */
    public JFrameAddPet() {
        initComponents();
        jPanelAddPet.setBorder(BorderFactory.createTitledBorder("Pets"));
        MaskFormatter mask = null;
        try {
            mask = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JFrameAddPet.class.getName()).log(Level.SEVERE, null, ex);
        }
        JFormattedTextField field = new JFormattedTextField(mask);
        field.setSize(txtPetBornDate.getSize());
        field.setEditable(true);
        this.jPanelAddPet.add(field);
        field.setLocation(jLabel2.getLocation().x+20,jLabel2.getLocation().y);
        field.setVisible(true);
        txtPetBornDate.setVisible(false);
        
        try {
            MaskFormatter formatter = new MaskFormatter("dd/MM/yyyy");
        } catch (ParseException ex) {
            Logger.getLogger(JFrameAddPet.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtPetBornDate.setFormatterFactory(null);
        loadOwnersInCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAddPet = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPetBreed = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPetBornDate = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPetName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbPetOwner = new javax.swing.JComboBox();
        btnAddPet = new javax.swing.JButton();
        btnCancelPet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Data de Nascimento:");

        txtPetBornDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.LONG))));

        jLabel3.setText("Raça:");

        jLabel4.setText("Dono:");

        cmbPetOwner.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddPet.setText("Adicionar");
        btnAddPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPetActionPerformed(evt);
            }
        });

        btnCancelPet.setText("Cancelar");
        btnCancelPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelPetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddPetLayout = new javax.swing.GroupLayout(jPanelAddPet);
        jPanelAddPet.setLayout(jPanelAddPetLayout);
        jPanelAddPetLayout.setHorizontalGroup(
            jPanelAddPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddPetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelAddPetLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPetBreed))
                    .addGroup(jPanelAddPetLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPetOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAddPetLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtPetBornDate))
                    .addGroup(jPanelAddPetLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPetName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddPetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddPet)
                .addGap(99, 99, 99))
            .addGroup(jPanelAddPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddPetLayout.createSequentialGroup()
                    .addContainerGap(153, Short.MAX_VALUE)
                    .addComponent(btnCancelPet)
                    .addGap(20, 20, 20)))
        );
        jPanelAddPetLayout.setVerticalGroup(
            jPanelAddPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddPetLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelAddPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPetBornDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPetBreed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbPetOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddPet))
            .addGroup(jPanelAddPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddPetLayout.createSequentialGroup()
                    .addContainerGap(124, Short.MAX_VALUE)
                    .addComponent(btnCancelPet)
                    .addGap(1, 1, 1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAddPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAddPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelPetActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelPetActionPerformed

    private void btnAddPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPetActionPerformed
        Pets p = new Pets();
        p.setName(txtPetName.getText());
        p.setBreed(txtPetBreed.getText());

        java.util.Date d = new java.util.Date();

        GregorianCalendar calendar = new GregorianCalendar();
        calendar.setGregorianChange(null);
        /*DateFormat df = new SimpleDateFormat();
         GregorianCalendar date = (GregorianCalendar) Calendar.getInstance();
         try {
         date.setTime(df.parse(txtPetBornDate.getText()));
         } catch (ParseException ex) {
         Logger.getLogger(JFrameAddClient.class.getName()).log(Level.SEVERE, null, ex);
         }*/
        //p.setBornDate(date);
        PetsDAO pets = new PetsDAO();
        pets.insert(p);

    }//GEN-LAST:event_btnAddPetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAddPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAddPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAddPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAddPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAddPet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPet;
    private javax.swing.JButton btnCancelPet;
    private javax.swing.JComboBox cmbPetOwner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelAddPet;
    private javax.swing.JFormattedTextField txtPetBornDate;
    private javax.swing.JTextField txtPetBreed;
    private javax.swing.JTextField txtPetName;
    // End of variables declaration//GEN-END:variables

    private void loadOwnersInCombobox() {
        //DefaultComboBoxModel modelo= (DefaultComboBoxModel) cmbPetOwner.getModel();  
        //modelo.addElement("oi");  
        cmbPetOwner.removeAllItems();
        ArrayList<String> columns = new ArrayList<String>();

        columns.add("col1");
        columns.add("col2");
        columns.add("col3");

        DefaultComboBoxModel tableModel = new DefaultComboBoxModel(columns.toArray());
        cmbPetOwner.setModel(tableModel);
    }
}
